services:
    # Providers.
    da_paginator.pager_adapter_provider.advanced_callback:
        class: Da\PaginatorBundle\PagerAdapter\Provider\AdvancedCallbackAdapterProvider
        arguments: []
        tags:
            - { name: da_paginator.pager_adapter_provider, id: advanced_callback }

    da_paginator.pager_adapter_provider.callback:
        class: Da\PaginatorBundle\PagerAdapter\Provider\CallbackAdapterProvider
        arguments: []
        tags:
            - { name: da_paginator.pager_adapter_provider, id: callback }

    da_paginator.pager_adapter_provider.doctrine_orm:
        class: Da\PaginatorBundle\PagerAdapter\Provider\DoctrineORMAdapterProvider
        arguments: []
        tags:
            - { name: da_paginator.pager_adapter_provider, id: doctrine_orm }

    da_paginator.pager_adapter_provider.doctrine_mongodb:
        class: Da\PaginatorBundle\PagerAdapter\Provider\DoctrineODMMongoDBAdapterProvider
        arguments: []
        tags:
            - { name: da_paginator.pager_adapter_provider, id: doctrine_mongodb }

    da_paginator.pager_adapter_provider.array:
        class: Da\PaginatorBundle\PagerAdapter\Provider\ArrayAdapterProvider
        arguments: []
        tags:
            - { name: da_paginator.pager_adapter_provider, id: array }