services:
    # Renderers.
    da_paginator.renderer.bootstrap:
        class: Da\PaginatorBundle\View\Renderer\TwitterBootstrapRenderer
        arguments: [@templating, @translator]
        tags:
            - { name: da_paginator.renderer, id: bootstrap }